- name: Deploy to Azure Functions
  uses: Azure/functions-action@v1
  with:
    app-name: dj-functionapp-msi
    package: ./publish
    publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
